version: "3.8"

services:
  db:
    image: mysql:5.7
    # restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "chat_system_api_development"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - /opt/docker_mysql_v/mysql_data:/var/lib/mysql
      - /tmp/docker_mysql_v/mysqld:/var/run/mysqld
    # healthcheck:
    #   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    #   timeout: 20s
    #   retries: 10

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      #need to add this volume in volumes section {in same level of services section}
      - elastic-data:/usr/share/elasticsearch/data
    restart: unless-stopped
    ports:
      - "9201:9200"
      - "9301:9300"
    networks:
      - es_network
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 120

  redis:
    image: "redis:4.0.9"
    command: redis-server
    ports:
      - "10001:6379"
    volumes:
      - "redis_data:/data"

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - ".:/app" # app is working dir in Dockerfile
      - "/app/tmp" # don't mount tmp directory
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:10001/1

  api:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      #this value must like in db container
      - /tmp/docker_mysql_v/mysqld:/run/mysqld
    ports:
      - "3001:3000"
    #let's make the app service depend_on the db: service
    #so that when we use our rails app it refers to the database to store data and it is linked to the database.
    depends_on:
      - db
      - elasticsearch
    links:
      - db
      - elasticsearch
      - redis
    #Now we want to add the environment variables for the rails application.
    environment:
      RAILS_ENV: development
      # DB_USER: root
      # DB_NAME: "chat_system_api_development"
      # DB_PASSWORD: password
      # DB_ROOT_PASSWORD: password
      # DB_HOST: db

volumes:
  es_data:
    driver: local
  redis_data:
    driver: local # is already local by default

networks:
  es_network:
    driver: bridge
